# Generated by Django 3.2.6 on 2021-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='buyed_price',
            field=models.FloatField(default=-1, verbose_name='Precio de compra'),
        ),
    ]
