# Generated by Django 3.2.6 on 2021-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_buyed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='estimated_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio estimado'),
        ),
        migrations.AlterField(
            model_name='property',
            name='buyed_price',
            field=models.FloatField(verbose_name='Precio de compra'),
        ),
    ]
