# Generated by Django 3.2.4 on 2021-06-20 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='UUID-CSV',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
