[tool.black]
exclude = "migrations"

[tool.flake8]
# Flake8 doesn't support pyproject.toml yet (see .flake8 file):
# https://github.com/PyCQA/flake8/issues/234
max-line-length = 88

[tool.isort]
line_length = 88
force_single_line = "1"
known_first_party = ["accounts", "properties", "external_sources", "main"]
default_section = "THIRDPARTY"
skip = "*/migrations/*"
