# Generated by Django 3.2 on 2021-04-08 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_reference', models.TextField(verbose_name='RC')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('province', models.TextField(verbose_name='Provincia')),
                ('municipality', models.TextField(verbose_name='Municipio')),
                ('builded_surface', models.IntegerField(verbose_name='Metros cuadrados construidos')),
                ('participation_coefficient', models.FloatField(default=100, verbose_name='Coeficiente de participación en la parcela')),
                ('year_built', models.IntegerField(default=-1, verbose_name='Año de construcción')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localización')),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='CP')),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name='Tipo de propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Uso principal')),
            ],
        ),
        migrations.CreateModel(
            name='ReformType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name='Tipo de reforma')),
            ],
        ),
        migrations.CreateModel(
            name='Subplot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subplot_code', models.TextField(verbose_name='Código')),
                ('cadastral_qualification', models.TextField(verbose_name='Calificación')),
                ('cultivation_class', models.TextField(verbose_name='Tipo de cultivo')),
                ('surface', models.IntegerField(verbose_name='Superficie en metros cuadrados')),
                ('productive_intensity', models.TextField(verbose_name='Intensidad productiva')),
                ('cadastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastres.cadastre')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('princpial_use', models.TextField(verbose_name='Uso')),
                ('surface', models.IntegerField(verbose_name='Superficie en metros cuadrados')),
                ('reform_date', models.IntegerField(blank=True, null=True, verbose_name='Año de reforma')),
                ('cadastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastres.cadastre')),
                ('reform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastres.reformtype')),
            ],
        ),
        migrations.AddField(
            model_name='cadastre',
            name='primary_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastres.primaryuse'),
        ),
        migrations.AddField(
            model_name='cadastre',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastres.classtype'),
        ),
    ]
