# Generated by Django 3.2.6 on 2021-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastres', '0003_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='type',
            field=models.TextField(default='-1', verbose_name='Tipo via'),
        ),
    ]
