# Generated by Django 3.2.4 on 2021-06-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0005_auto_20210609_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historioco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('monthly_variation', models.FloatField(blank=True, null=True, verbose_name='Variación mensual')),
                ('quarterly_variation', models.FloatField(blank=True, null=True, verbose_name='Variación trimestral')),
                ('annual_variation', models.FloatField(blank=True, null=True, verbose_name='Variación anual')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.element')),
            ],
        ),
    ]
