# Generated by Django 3.2.4 on 2021-06-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historioco',
            old_name='type',
            new_name='geo_element',
        ),
    ]
