# Generated by Django 3.2.4 on 2021-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealista', '0002_rename_type_historioco_geo_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historioco',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
