# Generated by Django 3.2.4 on 2021-06-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20210609_1027'),
        ('idealista', '0003_alter_historioco_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historioco',
            new_name='Historic',
        ),
    ]
