# Generated by Django 3.2.4 on 2021-06-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealista', '0004_rename_historioco_historic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historic',
            old_name='geo_element',
            new_name='geo_zone',
        ),
    ]
