# Generated by Django 3.2.6 on 2021-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealista', '0005_rename_geo_element_historic_geo_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic',
            name='conf_low',
            field=models.FloatField(blank=True, null=True, verbose_name='Cota superior'),
        ),
        migrations.AddField(
            model_name='historic',
            name='conf_up',
            field=models.FloatField(blank=True, null=True, verbose_name='Cota inferior'),
        ),
        migrations.AddField(
            model_name='historic',
            name='value_type',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de valor'),
        ),
    ]
