# Generated by Django 3.2.6 on 2021-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealista', '0006_auto_20210824_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='value_type',
            field=models.TextField(default='current', verbose_name='Tipo de valor'),
        ),
    ]
