# Generated by Django 3.2.6 on 2021-08-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0006_auto_20210619_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pob_total', models.IntegerField(verbose_name='Población')),
                ('count_households', models.IntegerField(verbose_name='Numero viviendas')),
                ('avg_size_home', models.FloatField(verbose_name='Tamaño medio del hogar')),
                ('unemployment_rate', models.FloatField(verbose_name='Tasa de paro')),
                ('prop_without_studies', models.FloatField(verbose_name='Proporción sin estudios')),
                ('prop_without_university_studies', models.FloatField(verbose_name='Proporción sin estudios universitarios')),
                ('prop_with_university_studies', models.FloatField(verbose_name='Proporción con estudios universitarios')),
                ('density', models.FloatField(verbose_name='Densidad (Habit/Hab)')),
                ('avg_age', models.FloatField(verbose_name='Edad Media')),
                ('index_youth', models.FloatField(verbose_name='Indice de juventud')),
                ('index_dependency', models.FloatField(verbose_name='Indice de dependencia')),
                ('index_active_population', models.FloatField(verbose_name='Indice de población activa')),
                ('index_replacement_active_population', models.FloatField(verbose_name='Indice de remplazo de población activa')),
                ('prop_born_outside', models.FloatField(verbose_name='Proporción nacidos fuera de España')),
                ('geo_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.geozone')),
            ],
        ),
    ]
