# Generated by Django 3.2.6 on 2021-08-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleelement',
            name='price_level_missing',
        ),
    ]
