# Generated by Django 3.2.6 on 2021-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_googleelement_price_level_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleelement',
            name='price_level_missing',
            field=models.BooleanField(default=False, verbose_name='Falta Precio'),
        ),
    ]
