# Generated by Django 3.2.6 on 2021-08-24 07:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('price', models.TextField(verbose_name='Precio')),
                ('review', models.TextField(verbose_name='Valoración')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('query', models.TextField(verbose_name='Petición')),
                ('coord', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localización')),
                ('price_level', models.SmallIntegerField(verbose_name='Nivel Precio')),
                ('price_level_weights', models.FloatField(verbose_name='Peso Precio')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_cole.schooltype')),
            ],
        ),
    ]
