# Generated by Django 3.2.6 on 2021-08-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cole', '0002_auto_20210824_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='school',
            name='lon',
        ),
    ]
