# Generated by Django 3.2.6 on 2021-08-24 09:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cole', '0004_auto_20210824_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='school',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localización'),
        ),
    ]
