# Generated by Django 3.2 on 2021-06-03 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('cod_dis', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Nombre')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Poligono')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('cod_dis_bar', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Nombre')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Poligono')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.district')),
            ],
        ),
    ]
