# Generated by Django 3.2 on 2021-06-03 10:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Poligono'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Poligono'),
        ),
    ]
