# Generated by Django 3.2.4 on 2021-06-09 09:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20210603_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('cod_mun', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Nombre')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Poligono')),
            ],
        ),
    ]
