# Generated by Django 3.2.4 on 2021-06-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='municipality',
            field=models.ForeignKey(default=473, on_delete=django.db.models.deletion.CASCADE, to='geo.municipality'),
            preserve_default=False,
        ),
    ]
