# Generated by Django 3.2.4 on 2021-06-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealista', '0005_rename_geo_element_historic_geo_zone'),
        ('geo', '0005_auto_20210609_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='GeoLevel',
        ),
        migrations.RenameModel(
            old_name='Element',
            new_name='GeoZone',
        ),
    ]
